#!/usr/bin/python3
#SPDX-FileCopyrightText:2022 Tarou Sato<s21c1023nb@s.chibakoudai.jp>
#SPDX-License-Identifier:BSD-3-Clause


import sys
ans=0.0
for line in sys.stdin:
    line=line.rstrip()
    try:
        if int(line)>=10:
            ans=ans*int(line)
        else:
            ans+=int(line)
    except:
        if float(line)>=10:
            ans=ans*float(line)
        else:
            ans+=float(line)
    
print(ans)
